### ISSUE TITLE
Reproduction on full eval set

### ISSUE THREAD

**Issue by jiadingfang** [Michael-Equi/lfg-demo#1]
Hi LFG authors,

Thanks for the great work!

While the demo on 4 images is interesting, I would like to reproduce the results reported in the paper on the full eval set. Could you help illustrate how to do that?

Thanks in advance!

**Comment by robodhruv** [comment]
Hi Jiading!

Thanks for reaching out over Github and email, I am copying the email response for completeness. The current repo only supports the scoring mechanism and not the entire eval pipeline, which heavily depends on https://github.com/facebookresearch/home-robot. You can use the eval code linked [here](https://openreview.net/forum?id=PsV65r0itpo) to run a more complete eval on Habitat. I've also attached a sample objectnav agent for your perusal.

[objectnav_agent_lang.py](https://github.com/Michael-Equi/lfg-nav/files/13870109/objectnav_agent_lang.py.txt)

Let me know if you have any questions
Dhruv and @Michael-Equi

**Comment by robodhruv** [comment]
Please feel free to reopen the issue if you have more questions!
