### ISSUE TITLE
Reproduction for the paper result 

### ISSUE THREAD

**Issue by johncruyff14** [Michael-Equi/lfg-demo#2]
Hi there. Thank you for your precious insight and amazing work.
I wonder if you may release the complete code which could reproduce the eval result in HM3D,  which is demonstrated in your paper. 
I am little bit confused about the notebook you release and the simulated data used in the notebook, as I think it's not a complete navigation model without the other parts.
I would appreciate it so much if you could release your complete baselines! @robodhruv @Michael-Equi

**Comment by robodhruv** [comment]
Hi Ryan,

The current repo only supports the scoring mechanism and not the entire eval pipeline, which heavily depends on https://github.com/facebookresearch/home-robot. You can use the eval code linked [here](https://openreview.net/forum?id=PsV65r0itpo) to run a more complete eval on Habitat. I've also attached a sample objectnav agent for your perusal. Most baselines we used are already publicly released: most relevant being https://github.com/ybgdgh/L3MVN and https://github.com/devendrachaplot/Object-Goal-Navigation, let us know if you have any questions.

[objectnav_agent_lang.py](https://github.com/Michael-Equi/lfg-nav/files/13870109/objectnav_agent_lang.py.txt)

Let me know if you have any questions
Dhruv and @Michael-Equi

**Comment by johncruyff14** [comment]
Hi @robodhruv . Thanks for your reply. I have integrated your algo with some baselines before and it is amazing O(∩_∩)O~. Thx for your work.
